### ISSUE TITLE
Onetime.sh fails initial installation with errors

### ISSUE THREAD

**Issue by lmservas** [SUFandom/proot-distro-tui#7]
Upon attempting to install I receive the following error output:

onetime.sh: 9: printf: {0..15}: expected numeric value
onetime.sh: 9: printf: {0..15}: expected numeric value
\e[48;5;0m000\e[0m
onetime.sh: 16: Syntax error: Bad for loop variable

Google Pixel 4 XL - Android 12L Beta - Latest Termux Debug version from GitHub "Actions": termux-app_v0.118.0+8746db0-github-debug_arm64-v8a

**Comment by lmservas** [comment]
I removed the gradient test from onetime.sh and got further through the process before it errors with:

onetime.sh: 32: ./!main.sh: not found

**Comment by lmservas** [comment]
Okay I removed the ! from the last line of onetime.sh so it says ./main.sh instead of ./!main.sh and that was successful.

**Comment by SUFandom** [comment]
sh tends to not understand the gradient test script, it only works on BASH. and as for `./!main.sh` thank you for spotting it, will do fix in 1.8
